version: "3"
services:
  cartogateway:
    image: ${REPO}elcheapoais_cartogateway:latest
    environment:
      DATABASE: "${DATABASE}"
    networks:
      - elcheapoais
      
  concentrator:
    image: ${REPO}elcheapoais_concentrator:latest
    environment:
      DATABASE: "${DATABASE}"
      CONFIG: |
        {
            "connections": [
                {"direction": "source", "type": "listen", "listen": "tcp:1024"},
                {"direction": "destination", "type": "listen", "listen": "tcp:1025"},
                {"direction": "destination", "type": "connect", "connect": "tcp:cartogateway:1024"},
                {"direction": "destination", "type": "file", "pattern": "/data/elcheapoais-%(YMDHMS)s.txt", "size": 3}
            ]
        }
    volumes:
      - ${DATA}:/data
    ports:
      - "1024:1024"
      - "1025:1025"
    networks:
      - elcheapoais

  cartodb:
    image: ${REPO}elcheapoais_cartodb
    volumes:
      - ${DBSTORAGE}:/var/lib/postgresql
    ports:
      - "1027:80"
    environment:
      CARTO_HOSTNAME: ${HOST}
    hostname: ${HOST}
    networks:
      - elcheapoais

  manhole:
    image: ${REPO}elcheapoais_manhole
    volumes:
      - ${MANHOLE}:/ElcheapoAIS_manhole/ElcheapoAIS_manhole/database
    ports:
      - "1026:8000"
    networks:
      - elcheapoais

networks:
  elcheapoais:
